#!/bin/sh
# dosbox-x-gemini.sh — Gemini PDA DOSBox-X launcher.
#
# Installed as `bin/dosbox-x` by pkgs/dosbox-x-gemini.nix; the store paths
# below are substituted at build time.  Full rationale:
# docs/desktop-plumbing.md §DOSBox-X.
#
# Two problems, two fixes:
#   1. DOSBox-X's SDL2 input path is scancode/position based, so it ignores
#      the host `gemini` XKB layout and uses its own keyboard table.  The
#      Gemini is a UK-silkscreen unit, so force DOSBox-X's UK table (its
#      default is US).  `-set` is applied after the config file is loaded,
#      so this wins over a stale user setting but is still overridable by a
#      later user `-set`.
#   2. The Fn layer is XKB level 3 (Fn == kernel KEY_RIGHTALT), i.e. no
#      distinct scancode, so DOSBox-X cannot see F1..F10 / media keys at
#      all.  The mapper file adds `mod2+key_N` (RALT + number) binds to the
#      F1..F10 events.  It is seeded into the user config dir because
#      DOSBox-X looks for `mapperfile` (default mapper-dosbox-x.map) there
#      and the file is all-or-nothing: a partial file replaces the built-in
#      defaults, so it must be the complete set.  Generated by
#      bin/gen-dosbox-x-mapper.sh from the pinned dosbox-x source.
#
# Env: DOSBOX_X_GEMINI_MAPPER_RESET=1 re-seeds the mapper (backs up the old
# file first).  Set DOSBOX_X_GEMINI_NO_UK=1 to keep DOSBox-X's own layout.
set -eu

confdir="${XDG_CONFIG_HOME:-$HOME/.config}/dosbox-x"
mapper="$confdir/mapper-dosbox-x.map"
mkdir -p "$confdir"

if [ ! -e "$mapper" ]; then
  cp -f "@MAPPER@" "$mapper"
  chmod 644 "$mapper"
elif [ "${DOSBOX_X_GEMINI_MAPPER_RESET:-0}" = 1 ]; then
  cp -f "$mapper" "$mapper.pre-gemini.$(date +%Y%m%d%H%M%S)" 2>/dev/null || true
  cp -f "@MAPPER@" "$mapper"
  chmod 644 "$mapper"
elif ! grep -q 'key 30 mod2' "$mapper" 2>/dev/null; then
  echo "dosbox-x (gemini): $mapper has no Gemini Fn bindings — Fn+1..0" >&2
  echo "  will not produce F1..F10.  Re-run with DOSBOX_X_GEMINI_MAPPER_RESET=1" >&2
  echo "  to regenerate it (the old file is backed up first)." >&2
fi

if [ "${DOSBOX_X_GEMINI_NO_UK:-0}" = 1 ]; then
  exec "@DOSBOX_X@" "$@"
else
  exec "@DOSBOX_X@" -set "dos keyboardlayout=uk" "$@"
fi
